name: spoonshare
description: "Meals of Grace."
publish_to: 'none'
version: 1.6.1+5

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  google_sign_in: ^6.2.1
  persistent_bottom_nav_bar: ^5.0.2
  image_picker: ^1.0.7
  firebase_storage: ^11.6.0
  permission_handler: ^11.2.0
  flutter_launcher_icons: ^0.13.1
  device_info_plus: ^9.1.1
  url_launcher: ^6.2.3
  intl: 0.19.0
  google_maps_flutter: ^2.5.3
  location: ^5.0.3
  google_maps_webservice: ^0.0.20-nullsafety.5
  http: ^0.13.6
  uuid: ^4.3.3
  geocoding: ^2.1.1
  custom_info_window: ^1.0.1
  geolocator: ^11.0.0
  change_app_package_name: ^1.1.0
  flutter_screenutil: ^5.9.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  firebase_messaging: 14.7.9
  flutter_local_notifications: 17.0.0
  webview_flutter: ^4.7.0
  share_plus: ^7.2.2
  path_provider: ^2.1.3
  flutter_svg: ^2.0.9
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/images/
   - assets/icons/filled/
   - assets/icons/outlined/
   - assets/lang/en.json
   - assets/lang/mr.json
   - assets/lang/hi.json
   - assets/lang/ka.json

  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf
          
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 700


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/spoonshare_launcher.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/images/spoonshare_launcher.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

